config/routes.rb
Rails
  .application
  .routes
  .draw do
    devise_for :users

    root 'home#index'
    get 'home', to: 'home#index'

    resource :profile, only: %i[show edit update]
    resource :cart, only: [:show]
    resources :cart_items, only: %i[create update destroy]
    resources :orders, only: %i[index show create new]

    scope :admin do
      get 'dashboard', to: 'dashboard#index', as: :admin_dashboard
      resources :items, except: [:show]
      resources :categories, except: [:show]
      resources :orders, only: %i[index show] do
        member do
          patch :cancel
          patch :mark_paid
          patch :complete
        end
      end
    end
    
    resources :items, only: %i[index show]
    resources :categories, only: [:show]
  end

app/views/shared/_category.html.erb
<%= link_to category_path(category) do %>
  <div class="flex flex-col justify-center items-center gap-3 w-[150px] h-[150px] sm:w-[180px] sm:h-[180px]">
    <div class="w-[73%] h-[68%] rounded-full overflow-hidden border border-gray-300">
      <%= image_tag(category.image.attached? ? url_for(category.image) : 'unknown.jpeg', alt: category.name, class: 'w-full h-full hover:scale-110 transition-transform duration-300') %>
    </div>
    <p class="text-sm"><%= category.name %></p>
  </div>
<% end %>

app/views/shared/_fallback.html.erb
<div class="h-[70vh] w-full flex justify-center items-center">
  <div class="space-y-2 flex flex-col justify-center items-center">
    <%= image_tag 'no_product.avif', alt: 'No Item Found', class: 'w-[150px]' %>
    <p class="bruno"><%= text %></p>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="fixed bottom-8 right-6 space-y-2 z-50">
    <% flash.each do |type, message| %>
      <div
        class="flash-message px-4 py-3 text-[0.8rem] rounded-lg text-white
                  <%= type == 'alert' ? 'bg-red-500' : 'bg-green-500' %>
                  shadow-lg"
      >
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-black text-white py-4 text-center text-[0.8rem] mt-10">© Dinner Dash. All rights reserved.</footer>

app/views/shared/_header.html.erb
<main class="relative w-full h-[30vh] flex items-center justify-center bg-gray-800">
  <div class="absolute inset-0">
    <%= image_tag 'sub_ecommerce_bg.jpeg', alt: 'E-commerce Banner', class: 'w-full h-full object-cover' %>
    <div class="absolute inset-0 bg-black opacity-50"></div>
  </div>

  <div class="relative z-10 text-center text-white px-4">
    <h1 class="text-3xl sm:text-4xl md:text-[40px] font-extrabold mb-4">
      <%= text %>
    </h1>
  </div>
</main>

app/views/shared/_item.html.erb
<div class="group grow lg:grow-0 w-[47%] pb-4 sm:w-[270px] sm:h-72 border border-gray-300 rounded-xl relative overflow-hidden">
  <div class="w-full">
    <%= link_to "/items/#{item.slug}" do %>
      <div class="w-full sm:h-[200px] overflow-hidden">
        <%= image_tag(item.image.attached? ? url_for(item.image) : 'unknown.jpeg', alt: item.title, class: 'h-full w-full hover:scale-110 transition-transform duration-300') %>
      </div>
    <% end %>

    <div class="flex justify-between items-center px-3 pt-5">
      <div class="text-sm">
        <p class="text-[#4D4D4D]">
          <%= item.title %>
        </p>
        <p><%= number_to_currency(item.price, unit: '$') %></p>
        <div class="flex pt-1">
          <% 5.times do %>
            <i class="fa-solid fa-star text-yellow-300 text-[0.5rem]"></i>
          <% end %>
        </div>
      </div>

      <%= button_to cart_items_path(id: item.id), method: :post, data: { turbo_stream: true } do %>
        <div class="bg-[#F2F2F2] w-[35px] h-[35px] sm:w-12 sm:h-11 rounded-full flex justify-center items-center cursor-pointer">
          <%= image_tag 'bag.avif', alt: 'Cart Icon', class: 'w-5 cursor-pointer' %>
        </div>
        <%= hidden_field_tag :title, item.title %>
        <%= hidden_field_tag :price, item.price %>
        <%= hidden_field_tag :description, item.description %>
        <%= hidden_field_tag :quantity, 1 %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<turbo-frame id="modal">
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-opacity-40 backdrop-blur-xs">
    <div class="bg-white rounded-lg p-6 w-96">
      <h2 class="text-lg font-bold mb-4">Confirmation</h2>
      <p class="mb-4">Are you sure you want to perform this action?</p>
      <div class="flex justify-end gap-2">
        <button class="cancel-btn px-4 py-2 bg-gray-200 rounded-lg cursor-pointer">Cancel</button>
        <button class="confirm-btn px-4 py-2 bg-red-600 text-white rounded-lg cursor-pointer">Confirm</button>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/shared/_navbar.html.erb
<nav class="bg-black text-white relative" data-controller="navbar">
  <div class="max-w-6xl mx-auto flex justify-between items-center px-4 py-3">
    <div class="flex items-center gap-6">
      <%= image_tag 'logo.png', alt: 'Dinner Dash', width: '60' %>

      <ul class="hidden md:flex items-center gap-8 text-sm">
        <li><%= link_to 'Home', root_path, class: 'hover:text-gray-300 transition' %></li>
        <li><%= link_to 'Products', items_path, class: 'hover:text-gray-300 transition' %></li>
        <li id="cart_count">
          <%= link_to cart_path, class: "block hover:text-gray-300 transition relative" do %>
            Cart
            <% if cart_count > 0 %>
              <span id="navbar-cart-count" class="absolute -top-2 -right-4 bg-red-600 text-white text-xs font-semibold w-6 h-6 rounded-full flex items-center justify-center">
                <%= cart_count %>
              </span>
            <% end %>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to 'Orders', orders_path, class: 'hidden md:block hover:text-gray-300 transition' %></li>
        <% end %>

        <% if user_signed_in? && current_user.role === "admin" %>
          <li><%= link_to 'Admin', admin_dashboard_path, class: 'hidden md:block hover:text-gray-300 transition' %></li>
        <% end %>

        <%= form_with url: items_path, method: :get, class: "flex items-center text-[0.8rem]" do %>
          <%= text_field_tag :query, params[:query], placeholder: 'Search products...', class: 'px-3 py-2 border border-gray-600 rounded-lg focus:outline-none focus:ring-1 focus:ring-gray-800' %>
        <% end %>
      </ul>
    </div>

    <div class="flex items-center gap-6 text-[0.8rem]">
      <% if user_signed_in? %>
        <%= link_to profile_path do %>
          <div class="hidden md:flex items-center gap-3">
            <div class="w-10 h-10 rounded-full overflow-hidden">
              <%= image_tag(current_user.image.attached? ? url_for(current_user.image) : 'unknown.jpeg', alt: current_user.display_name) %>
            </div>
            <div class="text-[0.8rem]">
              <p><%= current_user.display_name %></p>
              <p><%= current_user.email %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: 'hidden md:block hover:text-gray-300 transition text-sm' %>
      <% end %>

      <button class="md:hidden flex items-center px-3 py-2 border rounded text-white border-white" data-action="click->navbar#toggle">
        <i class="fas fa-bars"></i>
      </button>
    </div>
  </div>

  <ul class="md:hidden hidden_custom flex items-center flex-col gap-4 px-4 pb-4 text-sm" data-navbar-target="menu">
    <li><%= link_to 'Home', root_path, class: 'hover:text-gray-300 transition' %></li>
    <li><%= link_to 'Products', items_path, class: 'hover:text-gray-300 transition' %></li>
    <li><%= link_to 'Cart', cart_path, class: 'hover:text-gray-300 transition relative' %></li>
    <% if user_signed_in? && current_user.role === "admin" %>
      <li><%= link_to 'Admin', admin_dashboard_path, class: 'hover:text-gray-300 transition relative' %></li>
    <% end %>

    <% if user_signed_in? %>
      <li><%= link_to 'Orders', orders_path, class: 'block hover:text-gray-300 transition' %></li>
      <li><%= link_to 'Profile', profile_path, class: 'hover:text-gray-300 transition' %></li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'hover:text-red-500 transition' %>
      </li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path, class: 'hover:text-gray-300 transition' %></li>
    <% end %>

    <%= form_with url: items_path, method: :get, class: "flex items-center text-[0.8rem]" do %>
      <%= text_field_tag :query, params[:query], placeholder: 'Search products...', class: 'px-3 py-2 border border-gray-600 rounded-lg focus:outline-none focus:ring-1 focus:ring-gray-800' %>
    <% end %>
  </ul>
</nav>

app/views/shared/_table_header.html.erb
<th class="px-6 py-3 text-left text-gray-500 text-sm font-medium"><%= table_header %></th>