config/routes.rb
Rails
  .application
  .routes
  .draw do
    devise_for :users

    root 'home#index'
    get 'home', to: 'home#index'

    resource :profile, only: %i[show edit update]
    resource :cart, only: [:show]
    resources :cart_items, only: %i[create update destroy]
    resources :orders, only: %i[index show create new]

    scope :admin do
      get 'dashboard', to: 'dashboard#index', as: :admin_dashboard
      resources :items, except: [:show]
      resources :categories, except: [:show]
      resources :orders, only: %i[index show] do
        member do
          patch :cancel
          patch :mark_paid
          patch :complete
        end
      end
    end
    
    resources :items, only: %i[index show]
    resources :categories, only: [:show]
  end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  has_one_attached :image, dependent: :purge_later

  before_validation :generate_slug, on: :create

  default_scope { order(created_at: :desc) }

  validates :slug, uniqueness: true, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }

   def to_param
    slug
   end

  private

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  LIMIT = 8
  before_action :set_page_params, only: [:index]
  before_action :authenticate_user!, except: [:show]
  before_action :find_category, only: %i[show edit update destroy]
  after_action :verify_authorized, except: %i[index show]
  after_action :verify_policy_scoped, only: [:index]

  def index
    @categories = policy_scope(Category).page(set_page_params[:page]).per(set_page_params[:limit] || LIMIT)
    authorize Category
  end

  def show; end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @category
  end

  def update
    authorize @category

    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category updated successfully'
    else
      flash.now[:alert] = @category.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    authorize @category

    if @category.destroy
      flash.now[:notice] = 'Item deleted successfully'
    else
      flash.now[:alert] = @category.errors.full_messages.to_sentence
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end

  def set_page_params
    params.permit(:limit, :page)
  end

  def find_category
    @category = Category.find_by!(slug: params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def category_table_headers
     ["Image", "Category Name", "Total Items", "Actions"]
    end
end

app/views/categories/_category.html.erb
<tr id="<%= dom_id(category) %>">
  <td class="px-6 py-2">
    <%= image_tag(category.image.attached? ? url_for(category.image) : 'unknown.jpeg', alt: category.name, class: 'w-10 h-10 object-cover rounded-sm') %>
  </td>
  <td class="px-6 py-2"><%= category.name %></td>
  <td class="pl-14 py-2"><%= category.items_count %></td>
  <td class="px-6 pt-6 flex gap-3">
    <%= link_to edit_category_path(category), class: "text-blue-600 hover:text-blue-800" do %>
      <i class="fa-regular fa-pen-to-square"></i>
    <% end %>

    <%= link_to category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-red-600 hover:text-red-800" do %>
      <i class="fa-regular fa-trash-can"></i>
    <% end %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |f| %>
  <%= render 'shared/admin/error', record: @category %>

  <div class="mb-4">
    <%= f.label :name, class: 'block text-gray-700 font-semibold mb-1' %>
    <%= f.text_field :name, class: 'w-full border border-gray-300 px-4 py-3 rounded-lg' %>
  </div>

  <div class="mb-4">
    <%= f.label :image, class: 'block text-gray-700 font-semibold mb-1' %>
    <%= f.file_field :image, class: 'w-full border border-gray-300 px-4 py-3 rounded-lg' %>

    <% if @category.image.attached? %>
      <div class="mt-2">
        <%= image_tag url_for(@category.image), class: 'w-20 h-20 rounded object-cover' %>
      </div>
    <% end %>
  </div>

  <div class="mt-6 w-full flex justify-end gap-3">
    <%= f.submit (@category.new_record? ? 'Create Category' : 'Update Category'), class: 'bg-blue-600 text-white px-4 py-3 rounded-lg hover:bg-blue-700 cursor-pointer' %>
    <%= link_to 'Cancel', categories_path, class: 'bg-red-500 text-white px-4 py-3 rounded-lg hover:bg-red-600 transition cursor-pointer' %>
  </div>
<% end %>

app/views/categories/destroy.turbo_stream.erb
<% if @category.destroyed? %>
  <%= turbo_stream.remove @category %>
  <%= turbo_stream.update "flash_messages" do %>
    <%= render 'shared/flash' %>
  <% end %>
<% else %>
  <%= turbo_stream.update "flash_messages" do %>
    <%= render 'shared/flash' %>
  <% end %>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, 'Update Category | Dinner Dash' %>

<div class="p-6 min-h-screen">
  <div class="flex items-center justify-center mt-4 mb-10">
    <h1 class="text-xl sm:text-2xl font-bold bruno">Edit Category</h1>
  </div>

  <div class="bg-white rounded-xl shadow-md p-6 max-w-xl mx-auto">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<% content_for :title, 'Categories | Dinner Dash' %>

<div class="p-4 min-h-screen">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-xl sm:text-2xl font-bold bruno">Categories</h1>
    <%= link_to new_category_path, class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition flex items-center" do %>
      <i class="fa-solid fa-plus mr-2"></i>
      Add Category
    <% end %>
  </div>

  <div class="bg-white rounded-xl overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <%= render partial: 'shared/table_header', collection: category_table_headers %>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% if @categories.any? %>
          <%= render @categories %>
        <% else %>
          <tr>
            <td colspan="4" class="px-6 text-center text-gray-500">
              <%= render 'shared/fallback', text: 'No Categories found' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% if @categories.any? %>
      <div class="w-full flex justify-center mt-8 text-sm">
        <%= paginate @categories %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, 'Create Category | Dinner Dash' %>

<div class="p-6 min-h-screen">
  <div class="flex items-center justify-center mt-4 mb-10">
    <h1 class="text-xl sm:text-2xl font-bold bruno">Create Category</h1>
  </div>

  <div class="bg-white rounded-xl shadow-md p-6 max-w-xl mx-auto">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<% content_for :title, "#{@category.name} | Dinner Dash" %>

<%= render 'shared/header', text: "#{@category.name} Items" %>

<div class="w-full min-h-[80vh] max-h-auto flex flex-wrap justify-center mt-10">
  <% if @items.any? %>
    <div class="w-[90%] xl:w-[65%] flex flex-wrap gap-2">
      <%= render partial: 'shared/item', collection: @items %>
    </div>

    <div class="w-full flex justify-center mt-8 text-sm">
      <%= paginate @items %>
    </div>
  <% else %>
    <%= render 'shared/fallback', text: 'No Item Found' %>
  <% end %>
</div>